# Generated by Django 5.1.7 on 2026-02-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_3_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_3_floor',
        ),
    ]
