# Generated by Cursor on 2026-03-07

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_3_floor'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialConsumption',
            new_name='ProductMaterialNorm',
        ),
        migrations.AlterField(
            model_name='productmaterialnorm',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Расход на единицу продукции'),
        ),
        migrations.CreateModel(
            name='CostingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overhead_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Процент накладных от суммы (материалы + труд). Например 10.00 = 10%', max_digits=6, verbose_name='Накладные, %')),
                ('overhead_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Фиксированные накладные расходы на 1 единицу продукции', max_digits=12, verbose_name='Накладные на единицу (сом)')),
                ('allocate_overhead_from_finance', models.BooleanField(default=False, help_text='Если включено, накладные дополнительно считаются как (сумма расходов по выбранным категориям) / (выпуск за период)', verbose_name='Распределять накладные из Finance')),
                ('overhead_period_days', models.PositiveIntegerField(default=30, help_text='За сколько дней брать расходы и выпуск для распределения накладных', verbose_name='Период распределения (дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('overhead_categories', models.ManyToManyField(blank=True, help_text='Категории расходов, которые считаются накладными (аренда, свет, транспорт и т.д.)', related_name='costing_settings', to='finance.expensecategory', verbose_name='Категории накладных')),
            ],
            options={
                'verbose_name': 'Настройки себестоимости',
                'verbose_name_plural': 'Настройки себестоимости',
            },
        ),
    ]




