# Generated by Cursor on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_costing_settings_and_norms'),
    ]

    operations = [
        migrations.AddField(
            model_name='costingsettings',
            name='labor_period_days',
            field=models.PositiveIntegerField(default=30, help_text='За сколько дней брать выплаты и выпуск для расчёта труда на единицу', verbose_name='Период для расчёта труда (дней)'),
        ),
        migrations.AddField(
            model_name='costingsettings',
            name='use_actual_labor',
            field=models.BooleanField(default=False, help_text='Если включено, труд считается по фактическим выплатам сотрудникам за период (фикс + сдельная) / выпуск', verbose_name='Использовать фактическую себестоимость труда'),
        ),
    ]


