# Generated by Django 5.1.7 on 2026-02-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='defect_penalty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='Штраф за брак'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12, verbose_name='Оплата за услугу'),
        ),
    ]
