# Generated by Django 5.1.7 on 2026-02-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0006_simplify_defects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
