# Generated by Django 5.1.7 on 2026-03-07 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0007_alter_defect_created_at'),
        ('factory_inventory', '0010_materialissuelog'),
        ('operations_workshops', '0006_workshoplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кол-во брака (кг)')),
                ('output_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кол-во сырья (кг)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reworks', to='defects.defect', verbose_name='Брак')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reworks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник переработки')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_reworks', to='factory_inventory.rawmaterial', verbose_name='Сырьё после переработки')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_reworks', to='operations_workshops.workshop', verbose_name='Цех переработки')),
            ],
            options={
                'verbose_name': 'Переработка брака',
                'verbose_name_plural': 'Переработки брака',
                'ordering': ['-created_at'],
            },
        ),
    ]
