# Generated by Django 5.1.7 on 2026-03-10 01:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_tasks', '0008_employeetask_additional_penalties_and_more'),
        ('factory_inventory', '0011_rawmaterial_purchase_price'),
        ('finished_goods', '0004_finishedgoodsale_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Себестоимость за единицу')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общая себестоимость')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Затраты на труд')),
                ('material_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Затраты на сырье')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Дата расчета')),
                ('finished_good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='finished_goods.finishedgood', verbose_name='Готовая продукция')),
            ],
            options={
                'verbose_name': 'Себестоимость готовой продукции',
                'verbose_name_plural': 'Себестоимость готовой продукции',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodLaborCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Затраты')),
                ('completed_quantity', models.PositiveIntegerField(default=0, verbose_name='Выполнено')),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_costs', to='finished_goods.finishedgoodcosting', verbose_name='Себестоимость')),
                ('employee_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_good_labor_costs', to='employee_tasks.employeetask', verbose_name='Задача сотрудника')),
            ],
            options={
                'verbose_name': 'Затраты на труд',
                'verbose_name_plural': 'Затраты на труд',
                'unique_together': {('costing', 'employee_task')},
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodMaterialCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Затраты')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Количество')),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_costs', to='finished_goods.finishedgoodcosting', verbose_name='Себестоимость')),
                ('material_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_good_material_costs', to='factory_inventory.materialconsumption', verbose_name='Расход сырья')),
            ],
            options={
                'verbose_name': 'Затраты на сырье',
                'verbose_name_plural': 'Затраты на сырье',
                'unique_together': {('costing', 'material_consumption')},
            },
        ),
    ]
