# Generated by Django 5.1.7 on 2026-02-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_payment_schedule_and_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_schedule',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('worker', 'Рабочий')], default='worker', max_length=20, verbose_name='Роль'),
        ),
    ]
