# Generated by Django 5.1.7 on 2026-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_payment_type_remove_user_work_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='user',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приёма'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=50, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Паспорт'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Фиксированная'), ('variable', 'Сдельная')], default='fixed', max_length=20, verbose_name='Тип оплаты'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_schedule',
            field=models.CharField(choices=[('day', 'Дневной (8-20)'), ('night', 'Ночной (20-8)')], default='day', max_length=20, verbose_name='График работы'),
        ),
    ]
