# Generated by Django 5.1.7 on 2026-02-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_contract_number_user_dismissal_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dismissal_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
    ]
