# Generated by Django 5.1.7 on 2026-02-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Месячный оклад сотрудника при фиксированном типе оплаты', max_digits=12, null=True, verbose_name='Фиксированная зарплата в месяц'),
        ),
        migrations.AddField(
            model_name='user',
            name='pay_category',
            field=models.CharField(blank=True, choices=[('A', 'Категория A'), ('B', 'Категория B'), ('C', 'Категория C')], help_text='Категория сотрудника для расчёта оклада и сдельной ставки', max_length=10, null=True, verbose_name='Категория оплаты'),
        ),
        migrations.AddField(
            model_name='user',
            name='piecework_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сколько платим за 1 кг выполненной работы для этого сотрудника', max_digits=10, null=True, verbose_name='Ставка за кг (сдельная)'),
        ),
    ]
