# Generated by Django 5.1.7 on 2026-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_fixed_salary_user_pay_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pay_category',
        ),
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=0, help_text='Кредит сотрудника (используется для расчета рейтинга)', verbose_name='Кредит'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=100, help_text='Рейтинг сотрудника (максимум 100)', verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер WhatsApp', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
