# Generated by Django 5.1.7 on 2026-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_pay_category_user_credit_user_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Если включено, пользователь не может пользоваться системой и будет перенаправлен на страницу блокировки', verbose_name='Заблокирован'),
        ),
    ]
