# Generated by Django 5.1.7 on 2026-02-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0006_materialconsumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='size',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна производителя'),
        ),
    ]
