# Generated by Django 5.1.7 on 2026-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0008_employee_material_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeematerialbalance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
