# Generated by Django 5.1.7 on 2026-03-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_inventory', '0009_alter_employeematerialbalance_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество до выдачи')),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Количество после выдачи')),
                ('source', models.CharField(choices=[('issue_page', 'Мобильная выдача со склада'), ('other', 'Другое')], default='issue_page', max_length=32, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_logs', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_logs', to='factory_inventory.rawmaterial', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Выдача материала (лог)',
                'verbose_name_plural': 'Выдачи материалов (лог)',
                'ordering': ['-created_at'],
            },
        ),
    ]
