# Generated by Django 5.1.7 on 2026-02-25 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_workshops', '0002_alter_workshop_manager_workshopmaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'worker']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_managed_workshops', to=settings.AUTH_USER_MODEL, verbose_name='Главный руководитель (мастер)'),
        ),
        migrations.AlterField(
            model_name='workshopmaster',
            name='master',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'worker']}, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_master_roles', to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
    ]
