# Generated by Django 5.1.7 on 2026-02-26 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_workshops', '0004_create_extrusion_and_packaging_workshops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeutralBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Всего произведено (кг/единиц)')),
                ('used_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Списано вторым цехом')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neutral_batches', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neutral_batches', to='operations_workshops.workshop', verbose_name='Цех-источник')),
            ],
            options={
                'verbose_name': 'Партия нейтральной зоны',
                'verbose_name_plural': 'Партии нейтральной зоны',
                'ordering': ['-created_at'],
            },
        ),
    ]
