# Generated by Django 5.1.7 on 2026-03-07 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_workshops', '0005_neutralbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='operations_workshops.workshop', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Лог цеха',
                'verbose_name_plural': 'Логи цехов',
                'ordering': ['-created_at'],
            },
        ),
    ]
