# Generated by Django 5.1.7 on 2026-03-07 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_workshops', '0007_create_storage_and_rework_workshops'),
        ('orders', '0011_add_preparation_specs'),
        ('products', '0007_costing_labor_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Всего произведено (кг/единиц)')),
                ('used_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Списано складом (ID3)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_zones', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник ID2')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_zones', to='orders.order', verbose_name='Заказ')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_zones', to='orders.orderitem', verbose_name='Позиция заказа')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_zones', to='products.product', verbose_name='Товар')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_zones', to='operations_workshops.workshop', verbose_name='Цех-источник (ID2)')),
            ],
            options={
                'verbose_name': 'Партия складской зоны',
                'verbose_name_plural': 'Партии складской зоны',
                'ordering': ['-created_at'],
            },
        ),
    ]
