# Generated by Django 5.1.7 on 2026-02-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_penalty_manual_and_more'),
        ('attendance', '0004_shift_and_penalty_manual'),
    ]

    operations = [
    ]
