# Generated by Django 5.1.7 on 2026-03-07 08:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_merge_20260227_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_per_hour', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='Штраф за час опоздания (сом)')),
                ('grace_period_minutes', models.IntegerField(default=10, verbose_name='Льготный период (минуты)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Настройки посещаемости',
                'verbose_name_plural': 'Настройки посещаемости',
            },
        ),
    ]
