# Generated by Django 5.1.7 on 2026-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
