# Generated by Django 5.1.7 on 2026-03-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_finance_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefinancetransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
